apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.viewCreatorJobConfig.name }}
  labels:
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
data:
  {{- toYaml .Values.viewCreatorJobConfig.data | nindent 2 }}
