apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.creator.allViews.jobName }}
  labels:
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook-weight": "10"
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  # Cancel job if it has not finished after 10 minutes
  activeDeadlineSeconds: 600
  # Keep the job's pod around for 15 minutes. This will be better once we implement pod crashes and errors
  # monitoring.
  ttlSecondsAfterFinished: 900
  template:
    spec:
      restartPolicy: OnFailure
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
    {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: {{ .Values.viewCreatorJobConfig.name }}
          configMap:
            name: {{ .Values.viewCreatorJobConfig.name }}
    {{- with .Values.nodeLabels }}
      nodeSelector:
    {{- toYaml . | nindent 8}}
    {{- end }}
      containers:
        - name: {{ .Values.creator.allViews.jobName }}
          image: "{{ include "creatorservice.image" . }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          resources:
            {{- toYaml .Values.creator.allViews.resources | nindent 12 }}
          env:
            - name: SERVICE_NAME
              value: "all-views"
            - name: CLUSTER_NAME
              value: "staging"
            - name: BOOTSTRAP_CONFIG_URI
              value: "file:///app/resources/configs"
            - name: JAVA_TOOL_OPTIONS
              value: {{ .Values.creator.allViews.javaOpts | quote }}
          volumeMounts:
            - name: {{ .Values.viewCreatorJobConfig.name }}
              mountPath: /app/resources/configs/common/staging/application.conf
              subPath: application.conf
  backoffLimit: 100
