# Utility tools
version: '2.4'
services:

# Handy tool for manually creating require attributes into mongo like entity type, its relationship, etc
config-bootstrapper:
  image: hypertrace/config-bootstrapper
  container_name: attributes-bootstrapper
  environment:
    - SERVICE_NAME=config-bootstrapper
    - ATTRIBUTE_SERVICE_HOST_CONFIG=hypertrace-federated-service
    - ATTRIBUTE_SERVICE_PORT_CONFIG=9001
    - ENTITY_SERVICE_HOST_CONFIG=hypertrace-federated-service
    - ENTITY_SERVICE_PORT_CONFIG=9001
    - MONGO_HOST=mongo