version: 2.1

executors:
  gradle_docker:
    docker:
      - image: cimg/openjdk:11.0
  helm:
    docker:
      - image: $DOCKER_REGISTRY/ai.traceable.build/helm-packager:0.1.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD

commands:
  gradle:
    description: "Run the provided gradle command"
    parameters:
      args:
        type: string
      when:
        default: "on_success"
        type: enum
        enum: ["on_fail", "on_success", "always"]
    steps:
      - run:
          name: << parameters.args >>
          command: ./gradlew << parameters.args >> --info --max-workers=2 -Dorg.gradle.jvmargs=-Xmx2g -Dorg.gradle.console=plain --continue
          when: << parameters.when >>

jobs:
  publish:
    executor: gradle_docker
    steps:
      - checkout
      - setup_remote_docker
      - gradle:
          args: :tag -Prelease
      - add_ssh_keys:
          fingerprints:
            - "0e:65:4d:83:e5:82:43:01:ae:c0:7c:d6:cd:df:bd:b8"
      - run: git push origin $(./gradlew -q :printVersion)
  validate-charts:
    executor: helm
    steps:
      - checkout
      - run:
          name: Helm Charts Lint and Template Render
          command: |
            helm repo add hypertrace https://traceableai.jfrog.io/traceableai/helm --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            helm dependency update ./data-services/
            helm lint ./data-services/
            helm template --dry-run ./data-services/
            helm dependency update ./platform-services/
            helm lint ./platform-services/
            helm template --dry-run ./platform-services/
  package-charts:
    executor: helm
    steps:
      - checkout
      - run:
          name: Package and Publish Helm Charts
          # Read the "name:" from Chart.yaml. The chart version is <chart-name>-<semver git tag>
          command: |
            helm repo add hypertrace https://traceableai.jfrog.io/traceableai/helm --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            helm dependency update ./data-services/
            helm package --version $(git describe --abbrev=0) --app-version $(git describe --abbrev=0) ./data-services/
            helm push-artifactory $(awk '/^name:/ {print $2}' ./data-services/Chart.yaml)-$(git describe --abbrev=0).tgz https://traceableai.jfrog.io/traceableai/helm --username $DOCKER_USERNAME --password $DOCKER_PASSWORD --skip-reindex
            helm dependency update ./platform-services/
            helm package --version $(git describe --abbrev=0) --app-version $(git describe --abbrev=0) ./platform-services/
            helm push-artifactory $(awk '/^name:/ {print $2}' ./platform-services/Chart.yaml)-$(git describe --abbrev=0).tgz https://traceableai.jfrog.io/traceableai/helm --username $DOCKER_USERNAME --password $DOCKER_PASSWORD --skip-reindex

workflows:
  version: 2
  validate-and-publish:
    jobs:
      - validate-charts:
          context: continuous_deployment
      - publish:
          context: ci-credentials
          requires:
            - validate-charts
          filters:
            branches:
              only:
                - master
      - package-charts:
          context: continuous_deployment
          requires:
            - publish
          filters:
            branches:
              only:
                - master
