# This extension enable the metrics pipeline
version: '2.4'
services:
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prometheus.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles" ]
    volumes:
      - ./prom.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"