version: '2.4'
services:

  hypertrace:
    image: hypertrace/hypertrace:main
    environment:
      - DATA_STORE_TYPE=postgres
      - POSTGRES_HOST=postgres
      - ZK_CONNECT_STR=zookeeper:2181/hypertrace-views
    ports:
      - 2020:2020
    healthcheck:
      start_period: 20s
    depends_on:
      document-store:
        condition: service_started
      kafka-zookeeper:
        condition: service_healthy
      pinot:
        condition: service_started

  document-store:
    image: postgres:13.1
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres