# This extension enable the metrics pipeline
version: '2.4'
services:
  # all-in-one ingestion pipeline for hypertrace
  hypertrace-ingester:
    image: traceableai-docker.jfrog.io/hypertrace/hypertrace-ingester:test
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - DEFAULT_TENANT_ID=__default
      - SPAN_GROUPBY_SESSION_WINDOW_INTERVAL=2
      - REPLICATION_FACTOR=1
      - ENTITY_SERVICE_HOST_CONFIG=hypertrace
      - ENTITY_SERVICE_PORT_CONFIG=9001
      - ATTRIBUTE_SERVICE_HOST_CONFIG=hypertrace
      - ATTRIBUTE_SERVICE_PORT_CONFIG=9001
      - CONFIG_SERVICE_HOST_CONFIG=hypertrace
      - CONFIG_SERVICE_PORT_CONFIG=9001
      - NUM_STREAM_THREADS=1
      - PRE_CREATE_TOPICS=true
      - PRODUCER_VALUE_SERDE=org.hypertrace.core.kafkastreams.framework.serdes.GenericAvroSerde
      - METRICS_PIPELINE_ENABLE=true
    ports:
      - 8099:8099
    depends_on:
      kafka-zookeeper:
        condition: service_healthy
      hypertrace:
        # service_started, not service_healthy as pinot and deps can take longer than 60s to start
        condition: service_started

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    command: [ "--config.file=/etc/prom.yml", "--storage.tsdb.path=/prometheus", "--web.console.libraries=/usr/share/prometheus/console_libraries", "--web.console.templates=/usr/share/prometheus/consoles" ]
    volumes:
      - ./prom.yml:/etc/prom.yml
    ports:
      - 9090:9090