name: e2e test
on:
  push:
    ranches:
      - parameterised-e2e
  pull_request:
    branches:
      - update-helm-charts

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with: 
          ref: parameterised-e2e

      - name: Start minikube
        run: minikube start
      - name: Install Hypertrace
        working-directory: kubernetes
        run: ./hypertrace.sh install --clean

      - name: Cluster Info
        if: ${{ failure() }}
        run: |
          df -h
          minikube logs
          minikube status

      - name: Waits for some stability
        working-directory: kubernetes
        run: |
          sleep 120 # you can decrease it but never increase it
          kubectl get pods -n hypertrace
      - name: Set up Minikube tunnel
        run: |
          mkdir /tmp/minikube-tunnel
          minikube tunnel > /tmp/minikube-tunnel/a.log &

      - name: Ingest traces
        working-directory: ./.github/graphql-e2e-tests/
        run: ./ingest-traces.sh

      - name: run GraphQL tests
        working-directory: ./.github/graphql-e2e-tests/
        run: |
          export HTUI_IP=$(kubectl get service hypertrace-ui -n hypertrace -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          ./gradlew run

      - name: run UI tests
        working-directory: ./.github/ui-e2e-tests/
        run: |
          npm install 
          npm audit fix
          CHROMEDRIVER_RELEASE="$(google-chrome --product-version)" && npm run install-web-driver -- --versions.chrome=${CHROMEDRIVER_RELEASE}
          npx protractor protractor.conf.js --suite smoke --baseUrl "http://${HTUI_IP}:2020"

      - name: Clean up
        if: ${{ always() }}
        working-directory: kubernetes
        run: |
          ./hypertrace.sh uninstall
          minikube delete

      - name: Clean up
        if: ${{ always() }}
        run: rm -r -f hypertrace



