on: 
  release:
    types:
      - created
      
name: Slack Notification on Release
jobs:
  slackNotification:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK}}
        SLACK_COLOR: '#3278BD'
        SLACK_ICON: https://hypertrace-docs.s3.amazonaws.com/ht.png
        SLACK_MESSAGE: 'New helm charts for Hypertrace have been released. You can find release notes here: https://github.com/hypertrace/hypertrace/blob/main/RELEASE_NOTES.md  :rocket:'
        SLACK_TITLE: Hypertrace has new release
        SLACK_USERNAME: Hypertrace release bot