{
 "title": "Hypertrace Ingestion Pipeline Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Spans Received Rate (1m)",
   "type": "graph",
   "description": "Number of raw spans received",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hypertrace_reported_spans_total[1m])"
    }
   ]
  },
  {
   "title": "Span Normalization Time (secs)",
   "type": "graph",
   "description": "Time taken in normalizing span",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "span_normalization_time_seconds",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Spans Normalize Rate (1m)",
   "type": "graph",
   "description": "Number of normalized spans",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hypertrace_reported_spans_processed_total[1m])"
    }
   ]
  },
  {
   "title": "Spans Per Trace",
   "type": "graph",
   "description": "Number of spans in a trace",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spans_per_trace" }
   ]
  },
  {
   "title": "Emitted Traces Rate (1m)",
   "type": "graph",
   "description": "Number of traces emitted",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hypertrace_emitted_traces_total[1m])"
    }
   ]
  },
  {
   "title": "Enriched Traces Rate (1m)",
   "type": "graph",
   "description": "Rate of enriched traces",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hypertrace_enriched_traces_total[1m])"
    }
   ]
  },
  {
   "title": "Enrichment Time (secs)",
   "type": "graph",
   "description": "Number of spans normalized",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hypertrace_trace_enrichment_latency_seconds",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Arrival Lag Secs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "arrival_lag_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{ app }}"
    }
   ]
  }
 ]
}