{
 "title": "Hypertrace Query Layer Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Gateway Service APIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency of Span Queries (secs)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "org_hypertrace_core_serviceframework_span_query_execution",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "QPS for Span Queries (1 mins)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(org_hypertrace_core_serviceframework_span_query_execution_count[1m])",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Latency of Entities Queries (secs)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "org_hypertrace_core_serviceframework_entities_query_execution",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "QPS for Entities Queries (1 mins)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(org_hypertrace_core_serviceframework_entities_query_execution_count[1m])",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Build Time of Entities Queries (secs)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "org_hypertrace_core_serviceframework_entities_query_build",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "QPS for Entities Build Queries (1 mins)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(org_hypertrace_core_serviceframework_entities_query_build_count[1m])",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Latency of Explorer Queries (secs)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "org_hypertrace_core_serviceframework_explore_query_execution",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "QPS for Explorer Queries (1 mins)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(org_hypertrace_core_serviceframework_explore_query_execution_count[1m])",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Latency of Trace Queries (secs)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "org_hypertrace_core_serviceframework_traces_query_execution",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "QPS for Trace Queries (1 mins)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(org_hypertrace_core_serviceframework_traces_query_execution_count[1m])",
       "legendFormat": "{{ quantile }}"
      }
     ]
    }
   ]
  },
  { "title": "Pinot Request Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Latency(secs) all-handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pinot_query_latency_seconds{quantile=\"0.99\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "QPS all-handlers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pinot_query_latency_seconds_count[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Latency(secs) span-event-view-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pinot_query_latency_seconds{handler=\"span-event-view-handler\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "QPS span-event-view-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pinot_query_latency_seconds_count{handler=\"span-event-view-handler\"}[1m])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Latency(secs) service-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pinot_query_latency_seconds{handler=\"service-handler\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "QPS service-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pinot_query_latency_seconds_count{handler=\"service-handler\"}[1m])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Latency(secs) api-traces-view-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pinot_query_latency_seconds{handler=\"api-traces-view-handler\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "QPS api-traces-view-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pinot_query_latency_seconds_count{handler=\"api-traces-view-handler\"}[1m])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Latency(secs) api-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pinot_query_latency_seconds{handler=\"api-handler\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "QPS api-handlerr",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pinot_query_latency_seconds_count{handler=\"api-handler\"}[1m])",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Latency(secs) interactions-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pinot_query_latency_seconds{handler=\"interactions-handler\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "QPS interactions-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pinot_query_latency_seconds_count{handler=\"interactions-handler\"}[1m])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Latency(secs) backend-entity-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pinot_query_latency_seconds{handler=\"backend-entity-handler\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "QPS backend-entity-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pinot_query_latency_seconds_count{handler=\"backend-entity-handler\"}[1m])",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Latency(secs) backend-traces-view-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pinot_query_latency_seconds{handler=\"backend-traces-view-handler\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "QPS backend-traces-view-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pinot_query_latency_seconds_count{handler=\"backend-traces-view-handler\"}[1m])",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "Latency(secs) trace-view-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pinot_query_latency_seconds{handler=\"trace-view-handler\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "QPS trace-view-handler",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pinot_query_latency_seconds_count{handler=\"trace-view-handler\"}[1m])",
     "legendFormat": "{{ app }}"
    }
   ]
  }
 ]
}